require("user.config.impatient")
require("user.config.cmp")
require("user.config.nvim-lspconf")
require('user.config.Comment')
require("user.config.nvim-tree")
require('user.config.aerial')
require("user.config.bufferline")
require("user.config.gitsigns")
require("user.config.lualine")
require("user.config.toggleterm")
-- require("user.config.nvim-notify")
require("user.config.nvim-autopairs")
require("user.config.treesitter")
require("user.config.indent-blankline")
require("user.config.telescope")
